/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_athou_difupdate_Bspatch */

#ifndef _Included_com_athou_difupdate_Bspatch
#define _Included_com_athou_difupdate_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_athou_difupdate_Bspatch
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_athou_difupdate_BsPatch_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
